[profile.default]
    block_timestamp = 1_727_740_800 # October 1, 2024 at 00:00 GMT
    src = "src"
    out = "out"
    libs = ["lib"]
    auto_detect_solc = false
    solc = "0.8.23"
    evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
